import { buildContext } from "../../builders/context";
import { getFormAttribute } from "../../builders/form-attributes";
import {
  enumKeyToClassName,
  generatedDir,
  generatedFileName,
  generatedSiblingImport,
  modelKeyToClassName,
  pathParamToDecoratorName,
  resolveApplicationKey,
} from "../../builders/naming";
import { operationMethodName, resourceToControllerClassName } from "../../builders/nestjs-naming";
import { mergeImportLines, normalizeControllerPath, resolveType } from "../../builders/type-mapping";
import { GeneratedFilePayload, InvocationForm } from "../../types";

function fileHeader(namespace: string, apiPrefix: string): string {
  return `/**
 * Generated by Forsyte Generator from ${namespace}
 * Consumer global prefix: ${apiPrefix} (apply via setGlobalPrefix — not part of @Controller paths)
 * Do not edit — regenerate from apibuilder.
 */
`;
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function httpDecorator(method: string, path?: string): string {
  const nestMethod = capitalize(method.toLowerCase());
  const routePath = normalizeControllerPath(path?.replace(/^\//, "") ?? "");
  return routePath ? `@${nestMethod}("${routePath}")` : `@${nestMethod}()`;
}

const HTTP_STATUS_ENUM: Record<string, string> = {
  "200": "OK",
  "201": "CREATED",
  "202": "ACCEPTED",
  "204": "NO_CONTENT",
};

function defaultStatusForMethod(method: string): number {
  if (method.toLowerCase() === "post") {
    return 201;
  }
  return 200;
}

function pickSuccessStatus(responses: Record<string, { type: string }>): string {
  for (const status of ["200", "201", "202", "204"]) {
    if (responses[status]) {
      return status;
    }
  }
  const twoxx = Object.keys(responses)
    .filter((status) => {
      const code = Number.parseInt(status, 10);
      return code >= 200 && code < 300;
    })
    .sort((a, b) => Number.parseInt(a, 10) - Number.parseInt(b, 10));
  return twoxx[0] ?? "200";
}

function httpCodeDecorator(method: string, successStatus: string): string | null {
  const status = Number.parseInt(successStatus, 10);
  if (status === defaultStatusForMethod(method)) {
    return null;
  }
  const enumName = HTTP_STATUS_ENUM[successStatus];
  if (enumName) {
    return `@HttpCode(HttpStatus.${enumName})`;
  }
  return `@HttpCode(${status})`;
}

function apiSuccessDecorator(successStatus: string, tsType: string): string {
  if (successStatus === "204" || tsType === "void") {
    return "@ApiNoContentResponse()";
  }

  const isArray = tsType.endsWith("[]");
  const baseType = isArray ? tsType.slice(0, -2) : tsType;
  if (baseType === "unknown") {
    return successStatus === "201" ? "@ApiCreatedResponse()" : "@ApiOkResponse()";
  }
  const arraySuffix = isArray ? ", isArray: true" : "";

  if (successStatus === "201") {
    return `@ApiCreatedResponse({ type: ${baseType}${arraySuffix} })`;
  }
  return `@ApiOkResponse({ type: ${baseType}${arraySuffix} })`;
}

function apiErrorDecorator(status: string, tsType?: string): string | null {
  switch (status) {
    case "401":
      return "@ApiUnauthorizedResponse()";
    case "404":
      return "@ApiNotFoundResponse()";
    case "409":
      return "@ApiConflictResponse()";
    case "422":
      return tsType ? `@ApiUnprocessableEntityResponse({ type: ${tsType} })` : "@ApiUnprocessableEntityResponse()";
    default:
      return `@ApiResponse({ status: ${status} })`;
  }
}

function addLocalDtoImports(type: string, context: ReturnType<typeof buildContext>, localDtoImports: Set<string>): void {
  const arrayMatch = /^\[(.+)\]$/.exec(type);
  if (arrayMatch) {
    addLocalDtoImports(arrayMatch[1], context, localDtoImports);
    return;
  }
  if (type.includes(".")) {
    return;
  }
  if (context.rootService.models?.[type] || context.rootService.unions?.[type]) {
    localDtoImports.add(modelKeyToClassName(type));
  }
}

function emitResourceController(
  resourceKey: string,
  context: ReturnType<typeof buildContext>,
  localDtoImports: Set<string>,
  externalImports: Set<string>,
): string {
  const resource = context.rootService.resources?.[resourceKey];
  if (!resource) {
    return "";
  }

  const controllerClass = resourceToControllerClassName(resourceKey);
  const controllerPath = normalizeControllerPath(resource.path);
  const blocks: string[] = [];
  const usedMethodNames = new Set<string>();

  for (const operation of resource.operations) {
    const methodName = operationMethodName(operation, usedMethodNames, resourceKey);
    const successStatus = pickSuccessStatus(operation.responses);
    const successResponse = operation.responses[successStatus];
    const { tsType: successType, imports: successImports } = resolveType(successResponse?.type ?? "unit", context);
    successImports.forEach((line) => externalImports.add(line));
    addLocalDtoImports(successResponse?.type ?? "unit", context, localDtoImports);

    const returnType = successType === "void" ? "void" : successType;
    const promiseReturn = `Promise<${returnType}>`;

    const methodParams: string[] = [];
    const pathSwaggerDecorators: string[] = [];
    const httpMethodDecorator = httpDecorator(operation.method, operation.path);

    for (const parameter of operation.parameters ?? []) {
      const camel = pathParamToDecoratorName(parameter.name);
      const tsType = parameter.type === "integer" ? "number" : "string";
      const pathPattern = `:${parameter.name}`;
      const normalizedOpPath = normalizeControllerPath(operation.path ?? "");
      const inPath =
        `${resource.path}/`.includes(pathPattern) ||
        normalizedOpPath.includes(`:${camel}`) ||
        (operation.path ?? "").includes(pathPattern);

      if (inPath) {
        pathSwaggerDecorators.push(`@ApiParam({ name: "${camel}" })`);
        methodParams.push(`@Param("${camel}") ${camel}: ${tsType}`);
      } else {
        pathSwaggerDecorators.push(`@ApiQuery({ name: "${camel}", required: ${parameter.required === true} })`);
        methodParams.push(`@Query("${camel}") ${camel}${parameter.required === false ? "?" : ""}: ${tsType}`);
      }
    }

    if (operation.body) {
      const { tsType: bodyType, imports: bodyImports } = resolveType(operation.body.type, context);
      bodyImports.forEach((line) => externalImports.add(line));
      addLocalDtoImports(operation.body.type, context, localDtoImports);
      methodParams.push(`@Body() body: ${bodyType}`);
    }

    const swaggerDecorators: string[] = [
      `@ApiOperation({ summary: "${(operation.description ?? methodName).replace(/"/g, '\\"')}" })`,
      apiSuccessDecorator(successStatus, returnType),
      ...Object.entries(operation.responses)
        .filter(([status]) => status !== successStatus)
        .map(([status, response]) => {
          if (response.type === "unit") {
            return apiErrorDecorator(status);
          }
          const { tsType, imports } = resolveType(response.type, context);
          imports.forEach((line) => externalImports.add(line));
          addLocalDtoImports(response.type, context, localDtoImports);
          return apiErrorDecorator(status, tsType);
        })
        .filter((decorator): decorator is string => decorator !== null),
    ];

    const httpCode = httpCodeDecorator(operation.method, successStatus);
    if (httpCode) {
      swaggerDecorators.splice(1, 0, httpCode);
    }

    const validationPipe = operation.body ? "\n  @UsePipes(new ValidationPipe({ whitelist: true, transform: true }))" : "";
    const routeAndDocDecorators = [httpMethodDecorator, ...swaggerDecorators, ...pathSwaggerDecorators].join("\n  ");

    const paramList = methodParams.length > 0 ? `\n    ${methodParams.join(",\n    ")},\n  ` : "";

    blocks.push(`  ${routeAndDocDecorators}${validationPipe}
  async ${methodName}(${paramList}): ${promiseReturn} {
    throw new NotImplementedException();
  }`);
  }

  const decoratorPath = controllerPath ? `'${controllerPath}'` : "''";
  return `@ApiTags("${controllerClass}")
@Controller(${decoratorPath})
export abstract class ${controllerClass} {
${blocks.join("\n\n")}
}`;
}

export async function generateNestJsControllers(form: InvocationForm): Promise<GeneratedFilePayload[]> {
  const context = buildContext(form);
  const resources = context.rootService.resources ?? {};
  const resourceKeys = Object.keys(resources);
  if (resourceKeys.length === 0) {
    return [];
  }

  const applicationKey = resolveApplicationKey(context.rootService);
  const apiPrefix = getFormAttribute(form, "api_prefix", "/v1alpha");
  const dir = generatedDir(applicationKey);
  const localDtoImports = new Set<string>();
  const externalImports = new Set<string>();

  const resourceBlocks = resourceKeys.map((key) =>
    emitResourceController(key, context, localDtoImports, externalImports),
  );

  const enumImports = context.sortedEnumKeys.map((enumKey) => enumKeyToClassName(enumKey));

  const importBlock = [
    'import { Body, Controller, Delete, Get, HttpCode, HttpStatus, NotImplementedException, Param, Patch, Post, Put, Query, UsePipes, ValidationPipe } from "@nestjs/common";',
    'import { ApiConflictResponse, ApiCreatedResponse, ApiNoContentResponse, ApiNotFoundResponse, ApiOkResponse, ApiOperation, ApiParam, ApiQuery, ApiResponse, ApiTags, ApiUnauthorizedResponse, ApiUnprocessableEntityResponse } from "@nestjs/swagger";',
    localDtoImports.size > 0
      ? `import { ${Array.from(localDtoImports).sort().join(", ")} } from "${generatedSiblingImport(applicationKey, "dtos")}";`
      : "",
    enumImports.length > 0
      ? `import { ${enumImports.join(", ")} } from "${generatedSiblingImport(applicationKey, "enums")}";`
      : "",
    ...mergeImportLines(externalImports),
  ]
    .filter(Boolean)
    .join("\n");

  const contents = `${fileHeader(context.rootService.namespace, apiPrefix)}${importBlock}\n\n${resourceBlocks.join("\n\n")}`;

  return [
    {
      name: generatedFileName(applicationKey, "controllers"),
      dir,
      contents,
    },
  ];
}
