import { INestApplication } from "@nestjs/common";
import { Test, TestingModule } from "@nestjs/testing";
import { json } from "express";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import request from "supertest";
import { AppModule } from "../src/app.module";

function loadFixture(name: string): object {
  return JSON.parse(readFileSync(join(__dirname, "fixtures", "forms", name), "utf8")) as object;
}

describe("Generator service (e2e)", () => {
  let app: INestApplication;

  beforeAll(async () => {
    const moduleFixture: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

    app = moduleFixture.createNestApplication({ bodyParser: false });
    app.use(json({ limit: "10mb" }));
    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  it("GET /_internal_/healthcheck", async () => {
    await request(app.getHttpServer()).get("/_internal_/healthcheck").expect(200).expect("healthy");
  });

  it("GET /generators lists forsyte generators", async () => {
    const response = await request(app.getHttpServer()).get("/generators").expect(200);
    expect(response.body).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ key: "forsyte_nestjs_dtos" }),
        expect.objectContaining({ key: "forsyte_nestjs_controllers" }),
      ]),
    );
  });

  it("GET /generators/:key returns metadata with attributes", async () => {
    await request(app.getHttpServer())
      .get("/generators/forsyte_nestjs_controllers")
      .expect(200)
      .expect((res) => {
        expect(res.body.key).toBe("forsyte_nestjs_controllers");
        expect(res.body.generate).toBeUndefined();
        expect(res.body.attributes).toEqual(
          expect.arrayContaining([
            expect.objectContaining({ name: "api_prefix", default: "/v1alpha" }),
            expect.objectContaining({ name: "bundle_imports" }),
          ]),
        );
      });
  });

  it("GET /generators/unknown returns 404", async () => {
    await request(app.getHttpServer()).get("/generators/unknown").expect(404);
  });

  it("POST /invocations/unknown returns 409", async () => {
    await request(app.getHttpServer())
      .post("/invocations/unknown")
      .send(loadFixture("healthcheck-invocation.json"))
      .expect(409);
  });

  it("POST /invocations without service returns 409", async () => {
    await request(app.getHttpServer())
      .post("/invocations/forsyte_nestjs_dtos")
      .send({ attributes: [] })
      .expect(409)
      .expect((res) => {
        expect(res.body[0].code).toBe("SERVICE_PAYLOAD_NOT_FOUND");
      });
  });

  it("POST /invocations/forsyte_nestjs_dtos for healthcheck", async () => {
    const response = await request(app.getHttpServer())
      .post("/invocations/forsyte_nestjs_dtos")
      .send(loadFixture("healthcheck-invocation.json"))
      .expect(200);

    expect(response.body.source).toBe("");
    const names = response.body.files.map((f: { name: string }) => f.name);
    expect(names).toContain("healthcheck-dtos.ts");
    expect(names).not.toContain("healthcheck-enums.ts");
    expect(response.body.files[0].dir).toBe("generated/healthcheck");
  });

  it("POST /invocations/forsyte_nestjs_dtos for address", async () => {
    const response = await request(app.getHttpServer())
      .post("/invocations/forsyte_nestjs_dtos")
      .send(loadFixture("address-invocation.json"))
      .expect(200);

    const names = response.body.files.map((f: { name: string }) => f.name);
    expect(names).toContain("address-enums.ts");
    expect(names).toContain("address-dtos.ts");
    response.body.files.forEach((file: { name: string; dir: string; contents: string }) => {
      expect(file.dir).toBe("generated/address");
      expect(file.contents.length).toBeGreaterThan(0);
      expect(file.contents).toContain("Generated by Forsyte Generator");
    });
  });

  it("POST /invocations/forsyte_nestjs_controllers for address", async () => {
    const response = await request(app.getHttpServer())
      .post("/invocations/forsyte_nestjs_controllers")
      .send(loadFixture("address-invocation.json"))
      .expect(200);

    const names = response.body.files.map((f: { name: string }) => f.name);
    expect(names).toContain("address-controllers.ts");
    const controllers = response.body.files.find((f: { name: string }) => f.name === "address-controllers.ts");
    expect(controllers.contents).toContain("Consumer global prefix:");
    expect(controllers.contents).toContain("export abstract class AddressesController");
    expect(controllers.contents).toContain("export abstract class HealthchecksController");
    expect(controllers.contents).toContain('@Post("parse")');
    expect(controllers.contents).toContain("parse(");
    expect(controllers.contents).toContain("findOne(");
    expect(controllers.contents).not.toContain("abstract findOne(");
    expect(controllers.contents).not.toContain('@POST("parse")');
    expect(controllers.contents).toContain("Promise<AddressDto>");
    expect(controllers.contents).not.toContain("AddressesPutAddressIdResponse");
    expect(controllers.contents).not.toContain("Hook(");
  });
});
