import { buildContext } from "../../builders/context";
import {
  enumKeyToClassName,
  generatedDir,
  generatedFileName,
  generatedSiblingImport,
  modelKeyToClassName,
  resolveApplicationKey,
  snakeToCamel,
} from "../../builders/naming";
import { mergeImportLines, resolveType } from "../../builders/type-mapping";
import { GeneratedFilePayload, InvocationForm } from "../../types";

function fileHeader(namespace: string): string {
  return `/**\n * Generated by Forsyte Generator from ${namespace}\n * Do not edit — regenerate from apibuilder.\n */\n`;
}

function isMapType(type: string): boolean {
  return type === "map" || type.startsWith("map[");
}

function isDateTimeType(type: string): boolean {
  return type === "date-time-iso8601";
}

function isEnumType(type: string, enumKeys: Set<string>): boolean {
  return enumKeys.has(type);
}

function parseDefaultValue(type: string, defaultValue: string): string {
  if (type === "boolean") {
    return defaultValue === "true" ? "true" : "false";
  }
  if (type === "integer" || type === "long") {
    return defaultValue;
  }
  if (type === "map" || type === "object" || type === "json") {
    if (defaultValue === "{}") {
      return "{}";
    }
    return defaultValue;
  }
  return JSON.stringify(defaultValue);
}

function validatorForField(
  type: string,
  required: boolean,
  field: { minimum?: number; maximum?: number; max_length?: number },
  enumKeys: Set<string>,
  isForm: boolean,
): string[] {
  const decorators: string[] = [];
  if (!required) {
    decorators.push("@IsOptional()");
  }

  if (isEnumType(type, enumKeys)) {
    decorators.push(`@IsEnum(${enumKeyToClassName(type)})`);
    return decorators;
  }

  if (isMapType(type) || type === "object" || type === "json") {
    decorators.push("@IsObject()");
    return decorators;
  }

  if (isDateTimeType(type)) {
    decorators.push("@Type(() => Date)");
    decorators.push("@IsDate()");
    return decorators;
  }

  switch (type) {
    case "string":
    case "uuid":
    case "date-iso8601":
      decorators.push("@IsString()");
      if (field.max_length !== undefined) {
        decorators.push(`@MaxLength(${field.max_length})`);
      }
      break;
    case "integer":
    case "long":
      decorators.push("@IsInt()");
      if (field.minimum !== undefined) {
        decorators.push(`@Min(${field.minimum})`);
      }
      if (field.maximum !== undefined) {
        decorators.push(`@Max(${field.maximum})`);
      }
      break;
    case "double":
    case "decimal":
      decorators.push("@IsNumber()");
      if (field.minimum !== undefined) {
        decorators.push(`@Min(${field.minimum})`);
      }
      if (field.maximum !== undefined) {
        decorators.push(`@Max(${field.maximum})`);
      }
      break;
    case "boolean":
      decorators.push("@IsBoolean()");
      break;
    default:
      break;
  }

  if (isForm && required && type === "string") {
    decorators.push("@IsNotEmpty()");
    decorators.push("@MinLength(1)");
  }

  return decorators;
}

function isFormModel(modelKey: string): boolean {
  return modelKey.endsWith("_form");
}

function emitEnum(enumKey: string, values: Array<{ name: string }>): string {
  const className = enumKeyToClassName(enumKey);
  const members = values.map((v) => `  ${toEnumMember(v.name)} = "${v.name}",`).join("\n");
  return `export enum ${className} {\n${members}\n}\n`;
}

function toEnumMember(name: string): string {
  return name.replace(/[^a-zA-Z0-9]/g, "_").toUpperCase();
}

function emitModelClass(
  modelKey: string,
  form: InvocationForm,
  enumKeys: Set<string>,
): { code: string; imports: Set<string> } {
  const context = buildContext(form);
  const model = form.service.models?.[modelKey];
  if (!model) {
    return { code: "", imports: new Set() };
  }

  const className = modelKeyToClassName(modelKey);
  const allImports = new Set<string>();
  const lines: string[] = [];
  const isForm = isFormModel(modelKey);

  for (const field of model.fields) {
    const propertyName = snakeToCamel(field.name);
    const { tsType, imports } = resolveType(field.type, context);
    imports.forEach((line) => allImports.add(line));

    const optional = field.required === false;
    const hasDefault = field.default !== undefined;
    const nullableSuffix = optional && field.type !== "boolean" ? " | null" : "";
    const propertyType = optional ? `${tsType}${nullableSuffix}` : tsType;
    const propertyMarker = optional ? "?" : hasDefault ? "" : "!";
    const defaultValue = field.default ?? "";
    const defaultInitializer = hasDefault ? ` = ${parseDefaultValue(field.type, defaultValue)}` : "";

    const apiPropertyArgs: string[] = [];
    if (hasDefault) {
      const defaultLiteral = parseDefaultValue(field.type, defaultValue);
      if (field.type === "string" || field.type === "uuid" || field.type === "date-iso8601") {
        apiPropertyArgs.push(`default: ${defaultLiteral}`);
      } else if (field.type === "boolean") {
        apiPropertyArgs.push(`default: ${defaultLiteral}`);
      } else if (field.type === "integer" || field.type === "long") {
        apiPropertyArgs.push(`default: ${defaultLiteral}`);
      } else if (isMapType(field.type) && field.default === "{}") {
        apiPropertyArgs.push("default: {}");
      }
    }

    const apiDecorator =
      optional || hasDefault
        ? `@ApiPropertyOptional(${apiPropertyArgs.length > 0 ? `{ ${apiPropertyArgs.join(", ")} }` : ""})`
        : "@ApiProperty()";

    lines.push(`  ${apiDecorator}`);
    lines.push("  @Expose()");
    validatorForField(field.type, !optional, field, enumKeys, isForm).forEach((decorator) => lines.push(`  ${decorator}`));
    if (!optional && field.type === "string" && !hasDefault && !isForm) {
      lines.push("  @IsNotEmpty()");
      lines.push("  @MinLength(1)");
    }
    lines.push(`  ${propertyName}${propertyMarker}: ${propertyType}${defaultInitializer};`);
    lines.push("");
  }

  const code = `export class ${className} {\n${lines.join("\n")}}\n`;
  return { code, imports: allImports };
}

function emitUnionTypeAlias(unionKey: string, form: InvocationForm): string {
  const union = form.service.unions?.[unionKey];
  if (!union) {
    return "";
  }

  const members = union.types.map((member) => modelKeyToClassName(member.type)).join(" | ");
  return `export type ${modelKeyToClassName(unionKey)} = ${members};\n`;
}

function buildEnumsFile(form: InvocationForm, applicationKey: string, dir: string): GeneratedFilePayload | null {
  const context = buildContext(form);
  const keys = context.sortedEnumKeys;
  if (keys.length === 0) {
    return null;
  }

  const body = keys.map((key) => emitEnum(key, form.service.enums?.[key]?.values ?? [])).join("\n");
  const contents = `${fileHeader(form.service.namespace)}\n${body}`;

  return {
    name: generatedFileName(applicationKey, "enums"),
    dir,
    contents,
  };
}

function buildDtosFile(form: InvocationForm, applicationKey: string, dir: string): GeneratedFilePayload | null {
  const context = buildContext(form);
  const enumKeys = new Set(context.sortedEnumKeys);
  const modelKeys = context.sortedModelKeys;
  const unionKeys = context.sortedUnionKeys;

  if (modelKeys.length === 0 && unionKeys.length === 0) {
    return null;
  }

  const importLines = new Set<string>([
    'import { ApiProperty, ApiPropertyOptional } from "@nestjs/swagger";',
    'import { Expose, Type } from "class-transformer";',
    'import { IsBoolean, IsDate, IsEnum, IsInt, IsNotEmpty, IsNumber, IsObject, IsOptional, IsString, Max, MaxLength, Min, MinLength } from "class-validator";',
  ]);

  if (enumKeys.size > 0) {
    const enumImports = [...enumKeys].map((key) => enumKeyToClassName(key)).join(", ");
    importLines.add(`import { ${enumImports} } from "${generatedSiblingImport(applicationKey, "enums")}";`);
  }

  const classBlocks: string[] = [];
  for (const modelKey of modelKeys) {
    const { code, imports } = emitModelClass(modelKey, form, enumKeys);
    imports.forEach((line) => importLines.add(line));
    classBlocks.push(code);
  }

  for (const unionKey of unionKeys) {
    classBlocks.push(emitUnionTypeAlias(unionKey, form));
  }

  const contents = `${fileHeader(form.service.namespace)}\n${mergeImportLines(importLines).join("\n")}\n\n${classBlocks.join("\n")}`;
  return {
    name: generatedFileName(applicationKey, "dtos"),
    dir,
    contents,
  };
}

export async function generateNestJsDtos(form: InvocationForm): Promise<GeneratedFilePayload[]> {
  const applicationKey = resolveApplicationKey(form.service);
  const dir = generatedDir(applicationKey);
  const files: GeneratedFilePayload[] = [];

  const enumsFile = buildEnumsFile(form, applicationKey, dir);
  if (enumsFile) {
    files.push(enumsFile);
  }

  const dtosFile = buildDtosFile(form, applicationKey, dir);
  if (dtosFile) {
    files.push(dtosFile);
  }

  return files;
}
